SuperERP/SuperERP.Web/Controllers/CadastroController.cs
using SuperERP.Vendas;
using SuperERP.Vendas.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SuperERP.Compras.DTO;

namespace SuperERP.Web.Controllers
{
    public class CadastroController : Controller
    {
        public ActionResult Empresa()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Empresa(Compras.DTO.EmpresaDTO empresa)

        {
            Compras.Service.EmpresaService.Cadastrar(empresa);
            return View();
        }

        public ActionResult Usuario()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Usuario(UsuarioDTO usuario)
        {

            Compras.Service.UsuarioService.Cadastrar(usuario);
            return View();
        }

        public ActionResult PessoaFisica()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PessoaFisica(PessoaFisicaDTO pessoa)
        {
            // var pessoaFisica = SuperERP.Vendas.Listar.PessoaFisica();

            var teste = new List<string>();
            return View();
        }

        public ActionResult PessoaJuridica()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PessoaJuridica(PessoaJuridicaDTO pessoa)
        {
            return View();
        }
    }
}

SuperERP/SuperERP.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SuperERP.Vendas.Service;
using SuperERP.Vendas.DTO;
using System.Text.RegularExpressions;

namespace SuperERP.Web.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.fisicas = ClienteService.ListaPessoasFisicas();
            ViewBag.juridicas = ClienteService.ListaPessoasJuridicas();
            return View();
        }

        public ActionResult Editar(int id, int tipo)
        {
            if (tipo == 1)
            {
                var pf = ClienteService.BuscaPF(id);
                return View("EditarPF", pf);
            }
            else if (tipo == 2)
            {
                var pj = ClienteService.BuscaPJ(id);
                return View("EditarPJ", pj);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Editar(FormCollection f)
        {
            // Pessoa Fisica
            if (f["pessoa"] == "1")
            {
                var pessoa = new PessoaFisicaDTO();

                pessoa.ID = Convert.ToInt32(f["ID"]);
                pessoa.Nome = f["Nome"];
                pessoa.CPF = new Regex(@"[^\d]").Replace(f["CPF"], "");
                pessoa.RG = new Regex(@"[^\d]").Replace(f["RG"], "");

                if (f["Email"] != null)
                {
                    pessoa.Email = f["Email"];
                    pessoa.Fone = new Regex(@"[^\d]").Replace(f["Fone"], "");
                    pessoa.Cargo = f["Cargo"];
                }

                if (f["Endereco"] != null)
                {
                    pessoa.Endereco = f["Endereco"];
                    pessoa.Numero = f["Numero"];
                    pessoa.Complemento = f["Complemento"];
                    pessoa.CEP = new Regex(@"[^\d]").Replace(f["CEP"], "");
                    pessoa.Bairro = f["Bairro"];
                    pessoa.Cidade = f["Cidade"];
                }
                ClienteService.EditaPessoaFisica(pessoa);
            }
            // Pessoa Juridica
            else if (f["pessoa"] == "2")
            {
                var pessoa = new PessoaJuridicaDTO();
                pessoa.ID = Convert.ToInt32(f["ID"]);
                pessoa.Nome = f["Nome"];
                pessoa.CNPJ = new Regex(@"[^\d]").Replace(f["CNPJ"], "");
                pessoa.RazaoSocial = f["RazaoSocial"];

                if (f["Email"] != null)
                {
                    pessoa.Email = f["Email"];
                    pessoa.Fone = new Regex(@"[^\d]").Replace(f["Fone"], "");
                    pessoa.Cargo = f["Cargo"];
                }

                if (f["Endereco"] != null)
                {
                    pessoa.Endereco = f["Endereco"];
                    pessoa.Numero = f["Numero"];
                    pessoa.Complemento = f["Complemento"];
                    pessoa.CEP = new Regex(@"[^\d]").Replace(f["CEP"], "");
                    pessoa.Bairro = f["Bairro"];
                    pessoa.Cidade = f["Cidade"];
                }
                ClienteService.EditaPessoaJuridica(pessoa);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(FormCollection f)
        {
            // Pessoa Fisica
            if (f["pessoa"] == "1")
            {
                var pessoa = new PessoaFisicaDTO();
                pessoa.Nome = f["Item1.Nome"];
                pessoa.CPF = new Regex(@"[^\d]").Replace(f["Item1.CPF"], "");
                pessoa.RG = new Regex(@"[^\d]").Replace(f["Item1.RG"], "");

                if(f["Item1.Email"] != null)
                {
                    pessoa.Email = f["Item1.Email"];
                    pessoa.Fone = new Regex(@"[^\d]").Replace(f["Item1.Fone"], "");
                    pessoa.Cargo = f["Item1.Cargo"];
                }

                if (f["Item1.Endereco"] != null)
                {
                    pessoa.Endereco = f["Item1.Endereco"];
                    pessoa.Numero = f["Item1.Numero"];
                    pessoa.Complemento = f["Item1.Complemento"];
                    pessoa.CEP = new Regex(@"[^\d]").Replace(f["Item1.CEP"], "");
                    pessoa.Bairro = f["Item1.Bairro"];
                    pessoa.Cidade = f["Item1.Cidade"];
                }
                ClienteService.CadastraPessoaFisica(pessoa);
            }
            // Pessoa Juridica
            else if (f["pessoa"] == "2")
            {
                var pessoa = new PessoaJuridicaDTO();
                pessoa.Nome = f["Item2.Nome"];
                pessoa.CNPJ = new Regex(@"[^\d]").Replace(f["Item2.CNPJ"], "");
                pessoa.RazaoSocial = f["Item2.RazaoSocial"];

                if (f["Item1.Email"] != null)
                {
                    pessoa.Email = f["Item1.Email"];
                    pessoa.Fone = new Regex(@"[^\d]").Replace(f["Item1.Fone"], "");
                    pessoa.Cargo = f["Item1.Cargo"];
                }

                if (f["Item1.Endereco"] != null)
                {
                    pessoa.Endereco = f["Item1.Endereco"];
                    pessoa.Numero = f["Item1.Numero"];
                    pessoa.Complemento = f["Item1.Complemento"];
                    pessoa.CEP = new Regex(@"[^\d]").Replace(f["Item1.CEP"], "");
                    pessoa.Bairro = f["Item1.Bairro"];
                    pessoa.Cidade = f["Item1.Cidade"];
                }
                ClienteService.CadastraPessoaJuridica(pessoa);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Excluir(int id, int tipo)
        {
            ClienteService.ExcluirCliente(id, tipo);
            return RedirectToAction("Index");
        }
    }
}

SuperERP/SuperERP.Web/Controllers/OrdemServicoController.cs
using System.Web.Mvc;
using SuperERP.Vendas.DTO;
using SuperERP.Vendas.Service;

namespace SuperERP.Web.Controllers
{
    public class OrdemServicoController : Controller
    {

        public ActionResult ListarTodasOrdens() // listar todos os itens ok
        {
            var listaOrdens = new OrdemServicoService().listOrdemServico();

            return View(listaOrdens); // view criada
        }

        public ActionResult DetalheOrdem(int id) // detalhes da ordem passada ok
        {
            var buscarOrdem = new OrdemServicoService().buscarOrdemServico(id);
            return View(buscarOrdem);  // view criada
        }

        public ActionResult CadastrarNovaOrdem() // chamar tela de cadastro ok
        {
            var ordemApp = new OrdemServicoService();
            var listServico = ordemApp.listarServicos();
            ViewBag.servicos = new SelectList(listServico, "ID", "Nome");

            var listStatus = ordemApp.listarStatus();
            ViewBag.Status = new SelectList(listStatus, "ID", "Nome");

            return View(); // view criada
        }

        [HttpPost]
        public ActionResult CadastrarNovaOrdem(OrdemServicoDTO ordemDTO) // receber objeto para gravar
        {
            if (ordemDTO != null)
            {
                var gravarOrdem = new OrdemServicoService();
                gravarOrdem.savarOrdemServico(ordemDTO);
            }
           // return RedirectToAction("detalheOrdem"); // passar o id da ordem cadastrada
            return RedirectToAction("ListarTodasOrdens");
        }

        public ActionResult EditarOrdemServico(int id)  // receber id do obj selecionado, buscar e mostrar na tela
        {
            var ordemApp = new OrdemServicoService();
            var listServico = ordemApp.listarServicos();
            ViewBag.servicos = new SelectList(listServico, "ID", "Nome");

            var listStatus = ordemApp.listarStatus();
            ViewBag.Status = new SelectList(listStatus, "ID", "Nome");

            var buscarOrdem = new OrdemServicoService().buscarOrdemServico(id);
            return View(buscarOrdem);  // view criada
        }

        [HttpPost]
        public ActionResult EditarOrdemServico(OrdemServicoDTO ordemDTO) // receber o obj editado e gravar
        {
            if (ordemDTO != null)
            {
                var  atualizarOrdem = new OrdemServicoService();
                atualizarOrdem.savarOrdemServico(ordemDTO);
            }

            return RedirectToAction("detalheOrdem", new {ordemDTO.ID }); // jogar para a tela de detalhes depois de gravar a edicao
        }

	}
}

SuperERP/SuperERP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SuperERP</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatable")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mask")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SuperERP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vendas</a>
                        <ul class="dropdown-menu">
                            <li><a>Clientes</a></li>
                            <li><a href="/VendasOrcamentos">Vendas e Orçamentos</a></li>
                            <li><a href="/OrdemServico/ListarTodasOrdens">Ordem de serviço</a></li>
                            <li><a>Parcelas a receber</a></li>
                            <li><a>Estoque</a></li>
                            <li><a>Nota fiscal de produto</a></li>
                            <li><a>Serviços</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="~/Views/Financeiro/Index.cshtml" class="dropdown-toggle" data-toggle="dropdown">Financeiro</a>
                        <ul class="dropdown-menu">
                            <li><a href="/Financeiro">Home do Módulo Financeiro</a></li>
                            <li><a href="/Movimentacoes">Movimentações</a></li>
                            <li><a href="/ContasBancarias">Contas Bancárias</a></li>
                            <li><a href="/Extrato">Extrato</a></li>
                            <li><a href="/ContasPagar">Contas a Pagar</a></li>
                            <li><a href="/ContasReceber">Contas a Receber</a></li>
                            <li><a href="/PlanoCategoria">Plano de Categoria</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Empresa", "Empresa", "Cadastro")</li>
                    <li>@Html.ActionLink("Usuario", "Usuario", "Cadastro")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Ordem de Servico", "ListarTodasOrdens", "OrdemServico")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SuperERP</p>
        </footer>
    </div>
</body>
</html>