SuperERP/SuperERP.Web/Controllers/EstoqueGeralController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperERP.Web.Controllers
{
    public class EstoqueGeralController : Controller
    {
        //
        // GET: /EstoqueGeral/

        public ActionResult Index()
        {
            var estoque = Vendas.Listar.Estoque();
            return View(estoque);
        }

        //
        // GET: /EstoqueGeral/Inventario/5

        public ActionResult Inventario(int id)
        {
            ViewBag.vendaAtivos = Vendas.Listar.VendaAtivosProduto(id);
            ViewBag.compraAtivos = Vendas.Listar.CompraAtivosProduto(id);
            return View();
        }

        //
        // GET: /EstoqueGeral/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /EstoqueGeral/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /EstoqueGeral/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /EstoqueGeral/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /EstoqueGeral/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /EstoqueGeral/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperERP/SuperERP.Web/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperERP.Web.Controllers
{
    public class VendasController : Controller
    {
        //
        // GET: /Vendas/
        public ActionResult Index()
        {
            return View();
        }
	}
}

SuperERP/SuperERP.Web/Views/EstoqueGeral/Index.cshtml
@model IEnumerable<SuperERP.Vendas.DTO.ProdutoEstoqueDTO>

@{
    ViewBag.Title = "Estoque Geral";
    int totalEmEstoque = 0;
    double custoTotal = 0;
}
<style>    
.clickable-row {
       cursor: pointer;
    }
</style>
<div class="container">
<h2>Estoque Geral</h2><hr />
    <div class="row">
        <table class="table table-hover col-lg-12">
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    Código
                </th>
                <th>
                    Unidade de Medida
                </th>
                <th>
                    Categoria
                </th>
                <th>
                    Valor Venda
                </th>
                <th>
                    Valor Custo
                </th>
                <th>
                    Estoque
                </th>
                <th>
                    Valor Total
                </th>
            </tr>

        @foreach (var item in Model) {
            totalEmEstoque += item.Estoque;
            custoTotal += item.Valor_Venda * item.Estoque;
            var valorTotalProduto = item.Valor_Venda * item.Estoque;
            <tr class="clickable-row" data-href='@Url.Action("Inventario", "EstoqueGeral", new { id = item.ID })'>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo_Cliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unidade_Medida.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor_Venda)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor_Custo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estoque)
                </td>
                <td>
                    @valorTotalProduto
                </td>
            </tr>
        }
        </table>
    </div>
    <div class="row">
        <div class="col-sm-8"></div>
        <div class="col-sm-4">
            <table class="table table-reflow striped">
                <tr>
                    <th class="bg-info">Quantidade total em estoque:</th>
                    <td>@totalEmEstoque</td>
                </tr>
                <tr>
                    <th class="bg-info">Valor total em estoque:</th>
                    <td>@custoTotal</td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function ($) {
    $(".clickable-row").click(function () {
        window.document.location = $(this).data("href");
    });
});

</script>

SuperERP/SuperERP.Web/Views/EstoqueGeral/Inventario.cshtml
@{
    ViewBag.Title = "Estoque Geral";
    int totalEmEstoque = 0;
}
<style>    
.clickable-row {
       cursor: pointer;
    }
</style>
<div class="container">
<h2>Estoque de Produto</h2><hr />
    <div class="row">
        <table class="table table-hover col-lg-12">
            <tr>
                <th>
                    Data
                </th>
                <th>
                    Movimentação
                </th>
                <th>
                    Cliente / Fornecedor
                </th>
                <th>
                    Vl. Unitário
                </th>
                <th>
                    Valor de Custo
                </th>
                <th>
                    Qt. Movimentada
                </th>
            </tr>

        @foreach (var item in ViewBag.vendaAtivos) {
            totalEmEstoque -= item.Quantidade;
            <tr class="clickable-row" data-href='@Url.Action("Venda", "Vendas", new { id = item.Venda.ID })'>
                <td>
                    @item.Venda.Data_Venda
                </td>
                <td>
                    Saída
                </td>
                <td>
                    @item.Venda.ClienteFornecedor.ID
                </td>
                <td>
                    @item.Produto.Valor_Venda
                </td>
                <td>
                    TODO: Pegar valor custo
                </td>
                <td>
                    @item.Quantidade
                </td>
            </tr>
        }
        @foreach (var item in ViewBag.compraAtivos) {
                totalEmEstoque += item.Quantidade;
                <tr class="clickable-row" data-href='@Url.Action("Compra", "Compras", new { id = item.Compra.ID })'>
                    <td>
                        @item.Compra.Data_Compra
                    </td>
                    <td>
                        Entrada
                    </td>
                    <td>
                        @item.Compra.ClienteFornecedor.ID
                    </td>
                    <td>
                        @item.Produto.Valor_Venda
                    </td>
                    <td>
                        TODO: Pegar valor custo
                    </td>
                    <td>
                        @item.Quantidade
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="row">
        <div class="col-sm-8"></div>
        <div class="col-sm-4">
            <table class="table table-reflow striped">
                <tr>
                    <th class="bg-info">Saldo Final:</th>
                    <td>@totalEmEstoque</td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.document.location = $(this).data("href");
        });
    });

</script>